name: snowflake pipeline
on:
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # install snowflake cli
      - name: Install snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5

      # Setup pipx ensurepath
      - name: Install ensurepath
        run: pipx ensurepath

      # Print all environment variables
      - name: displaying all environment variables
        run: echo $PATH
      
      # install dbt dependices
      - name: installing dbt cli
        run: |
          pip install dbt-core dbt-snowflake

      # check the dbt version
      - name: displaying the dbt version
        run: |
          dbt --version
          
